#!/usr/bin/env bash
set -e

if [ "$1" = "help" ]
  then
    echo "Desc. : adds the specified path to the PATH variable permanently"
    echo "Usage : ./uh-add-to-path (path)"
    echo "Eg.   : ./uh-add-to-path /path/to/be/added"
    exit 0;
fi

if [ -z "$1" ]; then
  echo "Path not specified"
  exit 0;
fi

if [ ! -d "$1" ]; then
  echo "Specified path $1 does not exist"
  exit 0;
fi
LINE="PATH=\$PATH:$1"

FILE=/etc/profile
grep -q "$LINE" "$FILE" || echo -e "\n$LINE" >> "$FILE"

echo "Appended line $LINE to $FILE"

source $FILE

echo "Added $1 to PATH successfully" 
echo "You may need to log in again for the changes to take effect"
echo "If you are unable to log out now run the following command to temporarily apply the changes in the terminal: source /etc/profile"
